plugins {
    id 'com.android.application'
}

android {
    namespace 'cn.unicorn369.HookEuicc'
    compileSdk 35

    defaultConfig {
        applicationId "cn.unicorn369.HookEuicc"
        minSdk 26
        targetSdk 35
        versionCode 101
        versionName "1.0.1"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    compileOnly 'io.github.libxposed:api:102.0.0-SNAPSHOT'
    //implementation 'io.github.libxposed:service:102.0.0-SNAPSHOT'
}
